# headers and icon 
title: DeepGiraffe
info: PhD @ KAIST, Now @ SAIT, Samsung Electronics
icon-pic: assets/img/giraffe_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
